#!/usr/bin/env bash

function _git_find_file() {
    local path_to_toplevel=$(git rev-parse --show-toplevel)
    if [ $? -eq 0 ]; then
        cd "$path_to_toplevel"
        local cmd="git ls-files"
        cmd+=" | awk '"
        cmd+='BEGIN{IGNORECASE=1} //'
        if [ -f "${path_to_toplevel}/.gitfindignore" ]; then
          for ignore in $(cat "${path_to_toplevel}/.gitfindignore")
          do
              cmd+=" && !/$ignore/"
          done
        fi
        for var in "$@"
        do
            # escape slashes
            cmd+=" && /${var//\//\\/}/"
        done
        cmd+="' | uniq"
        for file in `eval $cmd`; do
            echo "${file}"
        done
    fi
}

_git_find_file $@
