#!/usr/bin/env bash

function _git_find_file() {
    local path_to_toplevel=$(git rev-parse --show-toplevel)
    if [ $? -eq 0 ]; then
        cd "$path_to_toplevel"
        local cmd="git ls-files"
        for var in "$@"
        do
            cmd+=" | grep -i \"$var\""
        done
        cmd+=" | uniq"
        for file in `eval $cmd`; do
            echo "${file}"
        done
    fi
}

_git_find_file $@
